name: Build Flet APK
on:
  workflow_dispatch: # Allows you to start the build manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flet
        run: pip install flet

      - name: Build APK
        run: flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-flet-app
          path: build/apk/*.apk
